services:
  - type: web
    name: my-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python App.py
    preDeployCommand: pip install --upgrade pip
    pythonVersion: "3.11"